name: CI

on:
  [push]

jobs:
  apk:
    name: Generate APK
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: set up JDK 11
        uses: actions/setup-java@master
        with:
          java-version: 11
      - name: Build debug APK
        run: bash ./gradlew assembleDebug --stacktrace
             tree
      - name: Upload APK
        uses: actions/upload-artifact@master
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk
